/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 进程存活检查，不暴露上游细节。 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务和存储就绪检查；上游可以仍处于离线状态。 */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 返回控制台认证是否启用以及当前是否已认证。 */
        get: operations["getSession"];
        put?: never;
        /** 使用控制台令牌换取 HttpOnly Cookie。 */
        post: operations["createSession"];
        /** 清除控制台会话 Cookie。 */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 来源状态、capabilities 和采集器限制。 */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前快照、所选区间汇总、趋势点和简要排行。 */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按一个受支持维度聚合已保留连接。 */
        get: operations["getRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dimensions/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 返回指定网络、入站或出站值的历史序列。 */
        get: operations["getDimensionSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前已校准的活动连接，按最新优先排列。 */
        get: operations["getActiveConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 控制台保留的已关闭连接，按最新优先排列。 */
        get: operations["getRecentConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 用于来源状态和连接生命周期失效通知的下游 SSE。
         * @description 使用 HttpOnly 会话 Cookie，并在有限内存回放窗口内支持 Last-Event-ID。
         *     事件名包括 `hello`、`source.state`、`connection.open`、
         *     `connection.close` 和 `resync`。keepalive 注释不是应用事件。
         *     收到 `resync` 或回放缺口后，客户端必须重新请求对应 REST 数据。
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        LoginRequest: {
            token: string;
        };
        SessionInfo: {
            authEnabled: boolean;
            authenticated: boolean;
        };
        /** @enum {string} */
        SourceState: "connecting" | "online" | "stale" | "offline" | "unauthorized";
        MetaResponse: {
            /** @constant */
            apiVersion: "v1";
            appVersion: string;
            /** Format: date-time */
            generatedAt: string;
            source: components["schemas"]["SourceInfo"];
            capabilities: components["schemas"]["Capabilities"] | null;
            collector: components["schemas"]["CollectorInfo"];
        };
        SourceInfo: {
            state: components["schemas"]["SourceState"];
            displayName: string;
            /** Format: date-time */
            lastAttemptAt?: string | null;
            /** Format: date-time */
            lastSuccessAt?: string | null;
            lastErrorCode?: string | null;
            /** Format: date-time */
            historyAvailableFrom?: string | null;
        };
        Capabilities: {
            /** @constant */
            upstreamApiVersion: 1;
            endpoints: string[];
            exposeSensitive: boolean;
            rankingDimensions: components["schemas"]["RankingDimension"][];
            sensitiveDimensions: components["schemas"]["RankingDimension"][];
            recentConnectionLimit: number;
            recentTtlSeconds: number;
            topKSize: number;
            activePageLimit: number;
            /** @constant */
            cursorPagination: true;
            eventReplay: boolean;
        };
        CollectorInfo: {
            scrapeIntervalSeconds: number;
            persistIntervalSeconds: number;
            retentionSeconds: number;
            /** @constant */
            maxSeriesPoints: 720;
            channels: components["schemas"]["CollectorChannels"];
        };
        CollectorChannel: {
            state: components["schemas"]["SourceState"];
            /** Format: date-time */
            lastAttemptAt: string | null;
            /** Format: date-time */
            lastSuccessAt: string | null;
            lastErrorCode: string | null;
        };
        EventChannel: {
            state: components["schemas"]["SourceState"];
            /** Format: date-time */
            lastAttemptAt: string | null;
            /** Format: date-time */
            lastSuccessAt: string | null;
            lastErrorCode: string | null;
            reconnects: number;
            /** Format: date-time */
            lastEventAt: string | null;
            lastSequence: number;
        };
        CollectorChannels: {
            capabilities: components["schemas"]["CollectorChannel"];
            metrics: components["schemas"]["CollectorChannel"];
            connections: components["schemas"]["CollectorChannel"];
            events: components["schemas"]["EventChannel"];
        };
        StatusSnapshot: {
            /** Format: date-time */
            observedAt: string;
            version: string;
            uptimeSeconds: number;
            memoryBytes: number;
            goroutines: number;
            activeConnections: number;
            recentConnections: number;
            connectionsTotal: number;
            uploadBytesTotal: number;
            downloadBytesTotal: number;
            uploadBytesPerSecond: number | null;
            downloadBytesPerSecond: number | null;
        };
        TimeWindow: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            stepSeconds: number;
        };
        RangeTotals: {
            uploadBytes: number;
            downloadBytes: number;
            connections: number;
        };
        TimePoint: {
            /** Format: date-time */
            timestamp: string;
            uploadBytesPerSecond: number | null;
            downloadBytesPerSecond: number | null;
            activeConnections: number | null;
            memoryBytes: number | null;
            goroutines: number | null;
        };
        DimensionTimePoint: {
            /** Format: date-time */
            timestamp: string;
            uploadBytesPerSecond: number | null;
            downloadBytesPerSecond: number | null;
            connectionsPerSecond: number | null;
            activeConnections: number | null;
            delayMs: number | null;
        };
        DimensionSeriesResponse: {
            /** Format: date-time */
            generatedAt: string;
            window: components["schemas"]["TimeWindow"];
            /** @enum {string} */
            dimension: "network" | "inbound" | "outbound";
            value: string;
            series: components["schemas"]["DimensionTimePoint"][];
        };
        UrlTestResult: {
            outbound: string;
            delayMs: number;
            /** Format: date-time */
            measuredAt: string;
            ageSeconds: number;
        };
        CompactRanking: {
            value: string;
            uploadBytesPerSecond: number | null;
            downloadBytesPerSecond: number | null;
            activeConnections: number;
        };
        APIEndpointHealth: {
            endpoint: string;
            status: number;
            requestsTotal: number;
            requestsPerSecond: number | null;
            averageDurationMs: number | null;
            responseBytesPerSecond: number | null;
        };
        APIHealthSnapshot: {
            recentConnectionsCapacity: number;
            recentConnectionsUtilization: number | null;
            sseSubscribers: number;
            sseEventsTotal: number;
            sseEventsPerSecond: number | null;
            errorRate: number | null;
            endpoints: components["schemas"]["APIEndpointHealth"][];
        };
        OverviewResponse: {
            /** Format: date-time */
            generatedAt: string;
            sourceState: components["schemas"]["SourceState"];
            window: components["schemas"]["TimeWindow"];
            current: components["schemas"]["StatusSnapshot"] | null;
            rangeTotals: components["schemas"]["RangeTotals"] | null;
            series: components["schemas"]["TimePoint"][];
            topOutbounds: components["schemas"]["CompactRanking"][];
            urlTests: components["schemas"]["UrlTestResult"][];
            apiHealth: components["schemas"]["APIHealthSnapshot"] | null;
        };
        /** @enum {string} */
        RankingDimension: "network" | "inbound" | "outbound" | "rule" | "domain" | "destination_ip" | "source" | "process" | "user";
        /**
         * @default traffic
         * @enum {string}
         */
        RankingSort: "traffic" | "connections" | "download" | "upload";
        RankingItem: {
            value: string;
            uploadBytes: number;
            downloadBytes: number;
            connections: number;
            activeConnections: number;
            percentage: number;
        };
        RankingsResponse: {
            /** Format: date-time */
            generatedAt: string;
            window: components["schemas"]["TimeWindow"];
            dimension: components["schemas"]["RankingDimension"];
            sort: components["schemas"]["RankingSort"];
            total: number;
            data: components["schemas"]["RankingItem"][];
        };
        Connection: {
            id: string;
            /** @enum {string} */
            state: "active" | "closed";
            network: string;
            inbound: string;
            sourceIP?: string;
            sourcePort?: number;
            sourceMAC?: string;
            sourceHostname?: string;
            destinationIP?: string;
            destinationPort: number;
            domain?: string;
            process?: string;
            user?: string;
            outbound: string;
            outboundType: string;
            chain: string[];
            rule?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            closedAt: string | null;
            durationSeconds: number;
            upload: number;
            download: number;
        };
        ConnectionPage: {
            /** Format: date-time */
            generatedAt: string;
            total: number;
            limit: number;
            offset: number;
            data: components["schemas"]["Connection"][];
        };
        SourceStateEventData: {
            state: components["schemas"]["SourceState"];
            /** Format: date-time */
            lastSuccessAt?: string | null;
            errorCode?: string | null;
        };
        ResyncEventData: {
            /** @enum {string} */
            reason: "replay_gap" | "slow_consumer" | "upstream_reconnected" | "upstream_event_gap" | "server_restarted";
        };
        EventEnvelope: {
            sequence: number;
            /** Format: date-time */
            generatedAt: string;
            /** @enum {string} */
            type: "hello" | "source.state" | "connection.open" | "connection.close" | "resync";
            data: components["schemas"]["SourceStateEventData"] | components["schemas"]["Connection"] | components["schemas"]["ResyncEventData"] | Record<string, never>;
        };
        ErrorResponse: {
            error: components["schemas"]["ApiError"];
        };
        ApiError: {
            /** @example UPSTREAM_UNAUTHORIZED */
            code: string;
            message: string;
            requestId: string;
            retryable: boolean;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 请求格式错误。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 控制台会话缺失或无效。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 语法有效，但时间范围或筛选条件无法处理。 */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 已达到登录速率限制。 */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description API 或存储尚未就绪。 */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 便捷时间范围，不能与 from/to 同时使用。 */
        Range: "15m" | "1h" | "6h" | "24h" | "7d" | "30d" | "90d";
        /** @description 包含边界的 RFC3339 起点，必须与 to 成对且不能与 range 同时使用。 */
        From: string;
        /** @description 不包含边界的 RFC3339 终点，必须与 from 成对且不能与 range 同时使用。 */
        To: string;
        /** @description 请求的时间桶大小；服务可以增大它以限制最多 720 个点。 */
        Step: string;
        /** @description 在上游实际暴露的字段中进行不区分大小写搜索。 */
        Search: string;
        Network: string;
        Outbound: string;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API 和存储已就绪。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 已认证会话，并设置 sbox_observability_session。 */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话已清除。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 元数据和 capabilities。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOverview: {
        parameters: {
            query?: {
                /** @description 便捷时间范围，不能与 from/to 同时使用。 */
                range?: components["parameters"]["Range"];
                /** @description 包含边界的 RFC3339 起点，必须与 to 成对且不能与 range 同时使用。 */
                from?: components["parameters"]["From"];
                /** @description 不包含边界的 RFC3339 终点，必须与 from 成对且不能与 range 同时使用。 */
                to?: components["parameters"]["To"];
                /** @description 请求的时间桶大小；服务可以增大它以限制最多 720 个点。 */
                step?: components["parameters"]["Step"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 概述数据；首次成功采集前 current 可以为 null。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getRankings: {
        parameters: {
            query: {
                dimension: components["schemas"]["RankingDimension"];
                sort?: components["schemas"]["RankingSort"];
                limit?: number;
                /** @description 便捷时间范围，不能与 from/to 同时使用。 */
                range?: components["parameters"]["Range"];
                /** @description 包含边界的 RFC3339 起点，必须与 to 成对且不能与 range 同时使用。 */
                from?: components["parameters"]["From"];
                /** @description 不包含边界的 RFC3339 终点，必须与 from 成对且不能与 range 同时使用。 */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 根据保留连接生成排行，并合并查询时的活动连接。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description 请求的敏感维度已被上游关闭。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getDimensionSeries: {
        parameters: {
            query: {
                dimension: "network" | "inbound" | "outbound";
                value: string;
                /** @description 便捷时间范围，不能与 from/to 同时使用。 */
                range?: components["parameters"]["Range"];
                /** @description 包含边界的 RFC3339 起点，必须与 to 成对且不能与 range 同时使用。 */
                from?: components["parameters"]["From"];
                /** @description 不包含边界的 RFC3339 终点，必须与 from 成对且不能与 range 同时使用。 */
                to?: components["parameters"]["To"];
                /** @description 请求的时间桶大小；服务可以增大它以限制最多 720 个点。 */
                step?: components["parameters"]["Step"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 维度序列；缺失时间桶的指标为 null。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DimensionSeriesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getActiveConnections: {
        parameters: {
            query?: {
                /** @description 在上游实际暴露的字段中进行不区分大小写搜索。 */
                q?: components["parameters"]["Search"];
                network?: components["parameters"]["Network"];
                outbound?: components["parameters"]["Outbound"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 活动连接分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getRecentConnections: {
        parameters: {
            query?: {
                /** @description 便捷时间范围，不能与 from/to 同时使用。 */
                range?: components["parameters"]["Range"];
                /** @description 包含边界的 RFC3339 起点，必须与 to 成对且不能与 range 同时使用。 */
                from?: components["parameters"]["From"];
                /** @description 不包含边界的 RFC3339 终点，必须与 from 成对且不能与 range 同时使用。 */
                to?: components["parameters"]["To"];
                /** @description 在上游实际暴露的字段中进行不区分大小写搜索。 */
                q?: components["parameters"]["Search"];
                network?: components["parameters"]["Network"];
                outbound?: components["parameters"]["Outbound"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 近期已关闭连接分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                heartbeat?: string;
                /** @description 浏览器 EventSource 的回放回退参数；Last-Event-ID 请求头优先。 */
                lastEventId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件流；每个 data 行都是 EventEnvelope JSON 对象。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
